### PR TITLE
Revert datapages

### LINKED ISSUE #21: Automate builds with GitHub actions
We now depend on an additional gem called `jekyll-datapage-generator`. This requires us to manually build the site into the docs folder before pushing. We need to automate this process with a github action (or investigate removing this dependency).

### PR DESCRIPTION
**Pull request by isaiahzs**
- [x] Get rid of datapages gem for the show pages
- [x] Get rid of datapages gem for the event pages

### CODE REVIEW

**Comment by isaiahzs** [comment]
Should be good to go, give it a review for me and then we can merge it!

**Comment by spencerng** [comment]
Nice work! Some notes:

* The new slug system works well
* The shows collection system is great, should be a lot easier to edit now
* We should prepare to modify the assets/images directory paths for consistency with the show pages. Do you have thoughts on having separate directories for `show-banners`, `show-thumbnails`, and `show-slideshow` vs. all images under one show directory? The former would have banners under `/assets/show-banners/<year>/<quarter>/<slug>.jpg`, with the latter as `/assets/show-images/<year>/<quarter>/<slug>/banner.jpg`
* How should we work in the slideshow per show? Would we need to parameterize how many images exist for each show, or could we pattern match against the an assets folder if using pure Liquid/HTML/CSS? 

Suggested changes:

- [x] Fix *This is How it Goes* to Spring 2015
- [x] Group shows back into each academic year - saves on a bit of clutter. This could be done as an additional parameter on each show page perhaps. We should also retain the (reverse) chronological ordering as presented on the old show page

**Comment by isaiahzs** [comment]
> - We should prepare to modify the assets/images directory paths for consistency with the show pages. Do you have thoughts on having separate directories for show-banners, show-thumbnails, and show-slideshow vs. all images under one show directory? The former would have banners under /assets/show-banners/<year>/<quarter>/<slug>.jpg, with the latter as /assets/show-images/<year>/<quarter>/<slug>/banner.jpg
> - How should we work in the slideshow per show? Would we need to parameterize how many images exist for each show, or could we pattern match against the an assets folder if using pure Liquid/HTML/CSS?

Saving these for #22 :+1:

**Comment by isaiahzs** [comment]
Anything else? If not you're welcome to merge it whenever.

**Pull request merged**
